FROM fedora:rawhide
RUN dnf -y install gcc make valgrind strace servicelog libservicelog libservicelog-devel
RUN dnf -y install sqlite-devel bison flex librtas-devel libtool automake rpm-build git
COPY . /build/
WORKDIR /build
